In [24]:
                                                                            # kfold

In [32]:
import matplotlib.pyplot as plt;
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.datasets import load_iris


from sklearn.model_selection import StratifiedKFold 
from sklearn.model_selection import KFold
Fold = StratifiedKFold(n_splits=3)
kf = KFold(n_splits=3)

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

from sklearn.datasets import load_digits

from sklearn.model_selection import train_test_split

In [34]:
l_model= LogisticRegression(max_iter = 500)
S_model= RandomForestClassifier(n_estimators=100)
R_model= SVC()
digit = load_digits()


X_train, X_test, y_train, y_test= train_test_split(digit.data, digit.target, test_size=0.3)

def get_score(model, X_train, X_test, y_train, y_test ):
    model.fit(X_train,y_train)
    return model.score(X_test, y_test)

In [11]:
for train_index, test_index in kf.split(digit.data, digit.target):
    X_train, X_test, y_train, y_test = digit.data[train_index], digit.data[test_index],\
                                        digit.target[train_index], digit.target[test_index]

    print(get_score(l_model, X_train, X_test, y_train, y_test))
    print(get_score(S_model, X_train, X_test, y_train, y_test))
    print(get_score(R_model, X_train, X_test, y_train, y_test))

0.9248747913188647
0.9332220367278798
0.9666110183639399
0.9432387312186978
0.9599332220367279
0.9816360601001669
0.9148580968280468
0.9248747913188647
0.9549248747913188


In [17]:
from sklearn.model_selection import cross_val_score     #direct method
print(cross_val_score(l_model, digit.data, digit.target))
print(cross_val_score(S_model, digit.data, digit.target ))
print(cross_val_score(R_model, digit.data, digit.target))

[0.92222222 0.87222222 0.94150418 0.94150418 0.89693593]
[0.92777778 0.9        0.96100279 0.96935933 0.92200557]
[0.96111111 0.94444444 0.98328691 0.98885794 0.93871866]


In [15]:
                                                                        # hypertunning 

In [43]:
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC

# print(cross_val_score(SVC(kernel='rbf',gamma='auto', C=10), digit.data, digit.target , cv=5))
# print(cross_val_score(SVC(kernel='linear',gamma='auto', C=10), digit.data, digit.target, cv=5 ))
# print(cross_val_score(SVC(kernel='poly',gamma='auto', C=10), digit.data, digit.target, cv=5 ))
# print(cross_val_score(SVC(kernel='rbf',gamma='scale', C=10), digit.data, digit.target, cv=5 ))
# print(cross_val_score(SVC(kernel='rbf',gamma='auto', C=50), digit.data, digit.target , cv=5))
# print(cross_val_score(SVC(kernel='rbf',gamma='auto', C=100), digit.data, digit.target , cv=5))

# INSTEAD

kernel = ["rbf", "linear", "poly", "sigmoid"]
C = [10,20,30,40,50,60,70,80,90,100]
average_score = {}

for i in kernel:
    for j in C:
        k = cross_val_score(SVC(kernel=i, gamma="scale", C=j), digit.data, digit.target,  cv=5)
        average_score[i+"_"+str(j)] = np.average(k)

average_score





{'rbf_10': 0.9738502011761063,
 'rbf_20': 0.9738502011761063,
 'rbf_30': 0.9738502011761063,
 'rbf_40': 0.9738502011761063,
 'rbf_50': 0.9738502011761063,
 'rbf_60': 0.9738502011761063,
 'rbf_70': 0.9738502011761063,
 'rbf_80': 0.9738502011761063,
 'rbf_90': 0.9738502011761063,
 'rbf_100': 0.9738502011761063,
 'linear_10': 0.9476973073351903,
 'linear_20': 0.9476973073351903,
 'linear_30': 0.9476973073351903,
 'linear_40': 0.9476973073351903,
 'linear_50': 0.9476973073351903,
 'linear_60': 0.9476973073351903,
 'linear_70': 0.9476973073351903,
 'linear_80': 0.9476973073351903,
 'linear_90': 0.9476973073351903,
 'linear_100': 0.9476973073351903,
 'poly_10': 0.96884246363355,
 'poly_20': 0.96884246363355,
 'poly_30': 0.96884246363355,
 'poly_40': 0.96884246363355,
 'poly_50': 0.96884246363355,
 'poly_60': 0.96884246363355,
 'poly_70': 0.96884246363355,
 'poly_80': 0.96884246363355,
 'poly_90': 0.96884246363355,
 'poly_100': 0.96884246363355,
 'sigmoid_10': 0.7841132776230271,
 'sigmoid_20

In [63]:
# instead use gridSearchCV

from sklearn.model_selection import GridSearchCV
gscv = GridSearchCV(SVC(gamma="auto"),{
    "C":[1,10,50,100],
    "kernel": ["linear", "rbf"]
}, cv=5 )

gscv.fit(digit.data, digit.target)
print(gscv.cv_results_)

{'mean_fit_time': array([0.03874784, 0.29693327, 0.03699555, 0.42448688, 0.05579481,
       0.53472223, 0.05581231, 0.54477286]), 'std_fit_time': array([0.0021856 , 0.00656927, 0.00296681, 0.11926785, 0.00306591,
       0.05864929, 0.00497821, 0.01980502]), 'mean_score_time': array([0.00829077, 0.0904758 , 0.00799894, 0.12945085, 0.01341252,
       0.14073424, 0.01299963, 0.14857407]), 'std_score_time': array([7.83423295e-04, 2.82209973e-03, 3.14495706e-06, 2.93832829e-02,
       1.35444676e-03, 2.28660695e-02, 1.09354793e-03, 9.28379298e-03]), 'param_C': masked_array(data=[1, 1, 10, 10, 50, 50, 100, 100],
             mask=[False, False, False, False, False, False, False, False],
       fill_value=999999), 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf',
                   'linear', 'rbf'],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'C': 1, 'kernel': 'lin

In [75]:
print(gscv.best_params_)
print(gscv.best_score_)

{'C': 1, 'kernel': 'linear'}
0.9476973073351903


In [69]:
df = pd.DataFrame(gscv.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0       0.038748      0.002186         0.008291        0.000783        1   
1       0.296933      0.006569         0.090476        0.002822        1   
2       0.036996      0.002967         0.007999        0.000003       10   
3       0.424487      0.119268         0.129451        0.029383       10   
4       0.055795      0.003066         0.013413        0.001354       50   
5       0.534722      0.058649         0.140734        0.022866       50   
6       0.055812      0.004978         0.013000        0.001094      100   
7       0.544773      0.019805         0.148574        0.009284      100   

  param_kernel                          params  split0_test_score  \
0       linear    {'C': 1, 'kernel': 'linear'}           0.963889   
1          rbf       {'C': 1, 'kernel': 'rbf'}           0.411111   
2       linear   {'C': 10, 'kernel': 'linear'}           0.963889   
3          rbf      {'C': 10, 'kernel': 'rbf'}           0.452778   
4       linear   {'C': 50, 'kernel': 'linear'}           0.963889   
5          rbf      {'C': 50, 'kernel': 'rbf'}           0.452778   
6       linear  {'C': 100, 'kernel': 'linear'}           0.963889   
7          rbf     {'C': 100, 'kernel': 'rbf'}           0.452778   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.919444           0.966574           0.963788           0.924791   
1           0.450000           0.454039           0.448468           0.479109   
2           0.919444           0.966574           0.963788           0.924791   
3           0.469444           0.479109           0.479109           0.501393   
4           0.919444           0.966574           0.963788           0.924791   
5           0.469444           0.479109           0.479109           0.501393   
6           0.919444           0.966574           0.963788           0.924791   
7           0.469444           0.479109           0.479109           0.501393   

   mean_test_score  std_test_score  rank_test_score  
0         0.947697        0.020978                1  
1         0.448545        0.021761                8  
2         0.947697        0.020978                1  
3         0.476366        0.015784                5  
4         0.947697        0.020978                1  
5         0.476366        0.015784                5  
6         0.947697        0.020978                1  
7         0.476366        0.015784                5

In [73]:
k = df[["param_C", "param_kernel", "mean_test_score"]]
k

param_C param_kernel  mean_test_score
0        1       linear         0.947697
1        1          rbf         0.448545
2       10       linear         0.947697
3       10          rbf         0.476366
4       50       linear         0.947697
5       50          rbf         0.476366
6      100       linear         0.947697
7      100          rbf         0.476366